var repos = 
[
{
"id": 29544350,
"name": "Accordion",
"full_name": "ssettle3/Accordion",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/Accordion",
"description": "Assignment 08 @ TIY",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/Accordion",
"forks_url": "https://api.github.com/repos/ssettle3/Accordion/forks",
"keys_url": "https://api.github.com/repos/ssettle3/Accordion/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/Accordion/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/Accordion/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/Accordion/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/Accordion/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/Accordion/events",
"assignees_url": "https://api.github.com/repos/ssettle3/Accordion/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/Accordion/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/Accordion/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/Accordion/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/Accordion/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/Accordion/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/Accordion/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/Accordion/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/Accordion/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/Accordion/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/Accordion/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/Accordion/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/Accordion/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/Accordion/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/Accordion/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/Accordion/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/Accordion/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/Accordion/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/Accordion/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/Accordion/merges",
"archive_url": "https://api.github.com/repos/ssettle3/Accordion/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/Accordion/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/Accordion/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/Accordion/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/Accordion/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/Accordion/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/Accordion/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/Accordion/releases{/id}",
"created_at": "2015-01-20T18:18:57Z",
"updated_at": "2015-01-20T21:31:13Z",
"pushed_at": "2015-01-20T21:31:49Z",
"git_url": "git://github.com/ssettle3/Accordion.git",
"ssh_url": "git@github.com:ssettle3/Accordion.git",
"clone_url": "https://github.com/ssettle3/Accordion.git",
"svn_url": "https://github.com/ssettle3/Accordion",
"homepage": null,
"size": 0,
"stargazers_count": 0,
"watchers_count": 0,
"language": "CSS",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29224450,
"name": "Blue-Print",
"full_name": "ssettle3/Blue-Print",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/Blue-Print",
"description": "Bonus Assignment",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/Blue-Print",
"forks_url": "https://api.github.com/repos/ssettle3/Blue-Print/forks",
"keys_url": "https://api.github.com/repos/ssettle3/Blue-Print/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/Blue-Print/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/Blue-Print/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/Blue-Print/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/Blue-Print/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/Blue-Print/events",
"assignees_url": "https://api.github.com/repos/ssettle3/Blue-Print/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/Blue-Print/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/Blue-Print/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/Blue-Print/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/Blue-Print/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/Blue-Print/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/Blue-Print/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/Blue-Print/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/Blue-Print/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/Blue-Print/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/Blue-Print/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/Blue-Print/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/Blue-Print/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/Blue-Print/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/Blue-Print/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/Blue-Print/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/Blue-Print/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/Blue-Print/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/Blue-Print/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/Blue-Print/merges",
"archive_url": "https://api.github.com/repos/ssettle3/Blue-Print/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/Blue-Print/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/Blue-Print/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/Blue-Print/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/Blue-Print/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/Blue-Print/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/Blue-Print/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/Blue-Print/releases{/id}",
"created_at": "2015-01-14T03:04:01Z",
"updated_at": "2015-01-14T03:35:34Z",
"pushed_at": "2015-01-14T03:38:59Z",
"git_url": "git://github.com/ssettle3/Blue-Print.git",
"ssh_url": "git@github.com:ssettle3/Blue-Print.git",
"clone_url": "https://github.com/ssettle3/Blue-Print.git",
"svn_url": "https://github.com/ssettle3/Blue-Print",
"homepage": null,
"size": 388,
"stargazers_count": 0,
"watchers_count": 0,
"language": "CSS",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29413544,
"name": "DigiClock",
"full_name": "ssettle3/DigiClock",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/DigiClock",
"description": "Digital Clock using JavaScript",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/DigiClock",
"forks_url": "https://api.github.com/repos/ssettle3/DigiClock/forks",
"keys_url": "https://api.github.com/repos/ssettle3/DigiClock/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/DigiClock/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/DigiClock/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/DigiClock/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/DigiClock/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/DigiClock/events",
"assignees_url": "https://api.github.com/repos/ssettle3/DigiClock/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/DigiClock/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/DigiClock/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/DigiClock/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/DigiClock/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/DigiClock/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/DigiClock/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/DigiClock/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/DigiClock/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/DigiClock/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/DigiClock/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/DigiClock/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/DigiClock/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/DigiClock/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/DigiClock/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/DigiClock/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/DigiClock/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/DigiClock/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/DigiClock/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/DigiClock/merges",
"archive_url": "https://api.github.com/repos/ssettle3/DigiClock/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/DigiClock/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/DigiClock/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/DigiClock/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/DigiClock/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/DigiClock/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/DigiClock/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/DigiClock/releases{/id}",
"created_at": "2015-01-18T02:45:29Z",
"updated_at": "2015-01-19T04:48:25Z",
"pushed_at": "2015-01-19T22:36:49Z",
"git_url": "git://github.com/ssettle3/DigiClock.git",
"ssh_url": "git@github.com:ssettle3/DigiClock.git",
"clone_url": "https://github.com/ssettle3/DigiClock.git",
"svn_url": "https://github.com/ssettle3/DigiClock",
"homepage": null,
"size": 156,
"stargazers_count": 0,
"watchers_count": 0,
"language": "JavaScript",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29603986,
"name": "EtsyjQuery",
"full_name": "ssettle3/EtsyjQuery",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/EtsyjQuery",
"description": "",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/EtsyjQuery",
"forks_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/forks",
"keys_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/events",
"assignees_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/merges",
"archive_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/EtsyjQuery/releases{/id}",
"created_at": "2015-01-21T18:14:50Z",
"updated_at": "2015-01-25T17:13:05Z",
"pushed_at": "2015-01-26T01:28:21Z",
"git_url": "git://github.com/ssettle3/EtsyjQuery.git",
"ssh_url": "git@github.com:ssettle3/EtsyjQuery.git",
"clone_url": "https://github.com/ssettle3/EtsyjQuery.git",
"svn_url": "https://github.com/ssettle3/EtsyjQuery",
"homepage": null,
"size": 0,
"stargazers_count": 0,
"watchers_count": 0,
"language": "JavaScript",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 28970950,
"name": "First-Github",
"full_name": "ssettle3/First-Github",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/First-Github",
"description": "My first attempt at Github",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/First-Github",
"forks_url": "https://api.github.com/repos/ssettle3/First-Github/forks",
"keys_url": "https://api.github.com/repos/ssettle3/First-Github/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/First-Github/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/First-Github/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/First-Github/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/First-Github/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/First-Github/events",
"assignees_url": "https://api.github.com/repos/ssettle3/First-Github/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/First-Github/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/First-Github/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/First-Github/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/First-Github/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/First-Github/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/First-Github/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/First-Github/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/First-Github/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/First-Github/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/First-Github/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/First-Github/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/First-Github/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/First-Github/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/First-Github/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/First-Github/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/First-Github/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/First-Github/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/First-Github/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/First-Github/merges",
"archive_url": "https://api.github.com/repos/ssettle3/First-Github/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/First-Github/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/First-Github/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/First-Github/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/First-Github/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/First-Github/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/First-Github/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/First-Github/releases{/id}",
"created_at": "2015-01-08T15:02:58Z",
"updated_at": "2015-01-08T15:02:58Z",
"pushed_at": "2015-01-08T15:17:55Z",
"git_url": "git://github.com/ssettle3/First-Github.git",
"ssh_url": "git@github.com:ssettle3/First-Github.git",
"clone_url": "https://github.com/ssettle3/First-Github.git",
"svn_url": "https://github.com/ssettle3/First-Github",
"homepage": null,
"size": 100,
"stargazers_count": 0,
"watchers_count": 0,
"language": null,
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29866239,
"name": "FizzBuzz",
"full_name": "ssettle3/FizzBuzz",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/FizzBuzz",
"description": "A group of FizzBuzz's written in JavaScript",
"fork": true,
"url": "https://api.github.com/repos/ssettle3/FizzBuzz",
"forks_url": "https://api.github.com/repos/ssettle3/FizzBuzz/forks",
"keys_url": "https://api.github.com/repos/ssettle3/FizzBuzz/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/FizzBuzz/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/FizzBuzz/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/FizzBuzz/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/FizzBuzz/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/FizzBuzz/events",
"assignees_url": "https://api.github.com/repos/ssettle3/FizzBuzz/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/FizzBuzz/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/FizzBuzz/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/FizzBuzz/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/FizzBuzz/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/FizzBuzz/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/FizzBuzz/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/FizzBuzz/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/FizzBuzz/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/FizzBuzz/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/FizzBuzz/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/FizzBuzz/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/FizzBuzz/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/FizzBuzz/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/FizzBuzz/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/FizzBuzz/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/FizzBuzz/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/FizzBuzz/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/FizzBuzz/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/FizzBuzz/merges",
"archive_url": "https://api.github.com/repos/ssettle3/FizzBuzz/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/FizzBuzz/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/FizzBuzz/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/FizzBuzz/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/FizzBuzz/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/FizzBuzz/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/FizzBuzz/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/FizzBuzz/releases{/id}",
"created_at": "2015-01-26T15:09:15Z",
"updated_at": "2015-01-26T15:16:03Z",
"pushed_at": "2015-01-26T15:16:03Z",
"git_url": "git://github.com/ssettle3/FizzBuzz.git",
"ssh_url": "git@github.com:ssettle3/FizzBuzz.git",
"clone_url": "https://github.com/ssettle3/FizzBuzz.git",
"svn_url": "https://github.com/ssettle3/FizzBuzz",
"homepage": null,
"size": 0,
"stargazers_count": 0,
"watchers_count": 0,
"language": "JavaScript",
"has_issues": false,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29874530,
"name": "GitHub",
"full_name": "ssettle3/GitHub",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/GitHub",
"description": "Homework 10 @ TIY",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/GitHub",
"forks_url": "https://api.github.com/repos/ssettle3/GitHub/forks",
"keys_url": "https://api.github.com/repos/ssettle3/GitHub/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/GitHub/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/GitHub/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/GitHub/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/GitHub/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/GitHub/events",
"assignees_url": "https://api.github.com/repos/ssettle3/GitHub/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/GitHub/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/GitHub/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/GitHub/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/GitHub/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/GitHub/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/GitHub/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/GitHub/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/GitHub/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/GitHub/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/GitHub/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/GitHub/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/GitHub/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/GitHub/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/GitHub/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/GitHub/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/GitHub/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/GitHub/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/GitHub/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/GitHub/merges",
"archive_url": "https://api.github.com/repos/ssettle3/GitHub/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/GitHub/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/GitHub/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/GitHub/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/GitHub/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/GitHub/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/GitHub/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/GitHub/releases{/id}",
"created_at": "2015-01-26T18:13:21Z",
"updated_at": "2015-01-26T18:17:24Z",
"pushed_at": "2015-01-26T18:17:24Z",
"git_url": "git://github.com/ssettle3/GitHub.git",
"ssh_url": "git@github.com:ssettle3/GitHub.git",
"clone_url": "https://github.com/ssettle3/GitHub.git",
"svn_url": "https://github.com/ssettle3/GitHub",
"homepage": null,
"size": 0,
"stargazers_count": 0,
"watchers_count": 0,
"language": "JavaScript",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29256919,
"name": "JS-Calculator",
"full_name": "ssettle3/JS-Calculator",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/JS-Calculator",
"description": "Assignment 06 @ The Iron Yard",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/JS-Calculator",
"forks_url": "https://api.github.com/repos/ssettle3/JS-Calculator/forks",
"keys_url": "https://api.github.com/repos/ssettle3/JS-Calculator/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/JS-Calculator/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/JS-Calculator/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/JS-Calculator/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/JS-Calculator/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/JS-Calculator/events",
"assignees_url": "https://api.github.com/repos/ssettle3/JS-Calculator/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/JS-Calculator/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/JS-Calculator/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/JS-Calculator/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/JS-Calculator/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/JS-Calculator/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/JS-Calculator/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/JS-Calculator/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/JS-Calculator/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/JS-Calculator/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/JS-Calculator/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/JS-Calculator/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/JS-Calculator/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/JS-Calculator/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/JS-Calculator/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/JS-Calculator/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/JS-Calculator/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/JS-Calculator/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/JS-Calculator/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/JS-Calculator/merges",
"archive_url": "https://api.github.com/repos/ssettle3/JS-Calculator/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/JS-Calculator/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/JS-Calculator/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/JS-Calculator/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/JS-Calculator/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/JS-Calculator/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/JS-Calculator/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/JS-Calculator/releases{/id}",
"created_at": "2015-01-14T17:40:59Z",
"updated_at": "2015-01-15T00:16:32Z",
"pushed_at": "2015-01-15T00:21:14Z",
"git_url": "git://github.com/ssettle3/JS-Calculator.git",
"ssh_url": "git@github.com:ssettle3/JS-Calculator.git",
"clone_url": "https://github.com/ssettle3/JS-Calculator.git",
"svn_url": "https://github.com/ssettle3/JS-Calculator",
"homepage": null,
"size": 200,
"stargazers_count": 0,
"watchers_count": 0,
"language": "CSS",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29311155,
"name": "JS-HW7",
"full_name": "ssettle3/JS-HW7",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/JS-HW7",
"description": "Assignment 07 @ The Iron Yard",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/JS-HW7",
"forks_url": "https://api.github.com/repos/ssettle3/JS-HW7/forks",
"keys_url": "https://api.github.com/repos/ssettle3/JS-HW7/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/JS-HW7/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/JS-HW7/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/JS-HW7/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/JS-HW7/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/JS-HW7/events",
"assignees_url": "https://api.github.com/repos/ssettle3/JS-HW7/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/JS-HW7/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/JS-HW7/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/JS-HW7/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/JS-HW7/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/JS-HW7/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/JS-HW7/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/JS-HW7/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/JS-HW7/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/JS-HW7/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/JS-HW7/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/JS-HW7/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/JS-HW7/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/JS-HW7/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/JS-HW7/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/JS-HW7/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/JS-HW7/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/JS-HW7/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/JS-HW7/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/JS-HW7/merges",
"archive_url": "https://api.github.com/repos/ssettle3/JS-HW7/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/JS-HW7/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/JS-HW7/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/JS-HW7/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/JS-HW7/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/JS-HW7/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/JS-HW7/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/JS-HW7/releases{/id}",
"created_at": "2015-01-15T18:18:30Z",
"updated_at": "2015-01-18T02:36:55Z",
"pushed_at": "2015-01-18T02:36:55Z",
"git_url": "git://github.com/ssettle3/JS-HW7.git",
"ssh_url": "git@github.com:ssettle3/JS-HW7.git",
"clone_url": "https://github.com/ssettle3/JS-HW7.git",
"svn_url": "https://github.com/ssettle3/JS-HW7",
"homepage": null,
"size": 164,
"stargazers_count": 0,
"watchers_count": 0,
"language": "JavaScript",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29209273,
"name": "JS-Intro",
"full_name": "ssettle3/JS-Intro",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/JS-Intro",
"description": "Homework 5 @ The Iron Yard",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/JS-Intro",
"forks_url": "https://api.github.com/repos/ssettle3/JS-Intro/forks",
"keys_url": "https://api.github.com/repos/ssettle3/JS-Intro/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/JS-Intro/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/JS-Intro/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/JS-Intro/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/JS-Intro/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/JS-Intro/events",
"assignees_url": "https://api.github.com/repos/ssettle3/JS-Intro/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/JS-Intro/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/JS-Intro/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/JS-Intro/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/JS-Intro/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/JS-Intro/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/JS-Intro/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/JS-Intro/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/JS-Intro/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/JS-Intro/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/JS-Intro/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/JS-Intro/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/JS-Intro/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/JS-Intro/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/JS-Intro/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/JS-Intro/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/JS-Intro/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/JS-Intro/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/JS-Intro/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/JS-Intro/merges",
"archive_url": "https://api.github.com/repos/ssettle3/JS-Intro/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/JS-Intro/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/JS-Intro/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/JS-Intro/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/JS-Intro/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/JS-Intro/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/JS-Intro/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/JS-Intro/releases{/id}",
"created_at": "2015-01-13T20:23:43Z",
"updated_at": "2015-01-13T20:24:12Z",
"pushed_at": "2015-01-13T20:24:11Z",
"git_url": "git://github.com/ssettle3/JS-Intro.git",
"ssh_url": "git@github.com:ssettle3/JS-Intro.git",
"clone_url": "https://github.com/ssettle3/JS-Intro.git",
"svn_url": "https://github.com/ssettle3/JS-Intro",
"homepage": null,
"size": 100,
"stargazers_count": 0,
"watchers_count": 0,
"language": "JavaScript",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 28981146,
"name": "Octocats",
"full_name": "ssettle3/Octocats",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/Octocats",
"description": "Homework 2 @ The Iron Yard",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/Octocats",
"forks_url": "https://api.github.com/repos/ssettle3/Octocats/forks",
"keys_url": "https://api.github.com/repos/ssettle3/Octocats/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/Octocats/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/Octocats/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/Octocats/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/Octocats/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/Octocats/events",
"assignees_url": "https://api.github.com/repos/ssettle3/Octocats/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/Octocats/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/Octocats/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/Octocats/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/Octocats/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/Octocats/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/Octocats/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/Octocats/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/Octocats/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/Octocats/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/Octocats/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/Octocats/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/Octocats/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/Octocats/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/Octocats/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/Octocats/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/Octocats/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/Octocats/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/Octocats/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/Octocats/merges",
"archive_url": "https://api.github.com/repos/ssettle3/Octocats/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/Octocats/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/Octocats/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/Octocats/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/Octocats/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/Octocats/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/Octocats/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/Octocats/releases{/id}",
"created_at": "2015-01-08T19:03:04Z",
"updated_at": "2015-01-08T19:09:26Z",
"pushed_at": "2015-01-08T19:09:26Z",
"git_url": "git://github.com/ssettle3/Octocats.git",
"ssh_url": "git@github.com:ssettle3/Octocats.git",
"clone_url": "https://github.com/ssettle3/Octocats.git",
"svn_url": "https://github.com/ssettle3/Octocats",
"homepage": null,
"size": 100,
"stargazers_count": 0,
"watchers_count": 0,
"language": "CSS",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 29145833,
"name": "Sass-Intro",
"full_name": "ssettle3/Sass-Intro",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/Sass-Intro",
"description": "",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/Sass-Intro",
"forks_url": "https://api.github.com/repos/ssettle3/Sass-Intro/forks",
"keys_url": "https://api.github.com/repos/ssettle3/Sass-Intro/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/Sass-Intro/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/Sass-Intro/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/Sass-Intro/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/Sass-Intro/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/Sass-Intro/events",
"assignees_url": "https://api.github.com/repos/ssettle3/Sass-Intro/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/Sass-Intro/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/Sass-Intro/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/Sass-Intro/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/Sass-Intro/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/Sass-Intro/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/Sass-Intro/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/Sass-Intro/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/Sass-Intro/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/Sass-Intro/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/Sass-Intro/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/Sass-Intro/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/Sass-Intro/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/Sass-Intro/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/Sass-Intro/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/Sass-Intro/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/Sass-Intro/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/Sass-Intro/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/Sass-Intro/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/Sass-Intro/merges",
"archive_url": "https://api.github.com/repos/ssettle3/Sass-Intro/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/Sass-Intro/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/Sass-Intro/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/Sass-Intro/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/Sass-Intro/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/Sass-Intro/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/Sass-Intro/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/Sass-Intro/releases{/id}",
"created_at": "2015-01-12T16:52:10Z",
"updated_at": "2015-01-12T17:07:31Z",
"pushed_at": "2015-01-12T17:07:31Z",
"git_url": "git://github.com/ssettle3/Sass-Intro.git",
"ssh_url": "git@github.com:ssettle3/Sass-Intro.git",
"clone_url": "https://github.com/ssettle3/Sass-Intro.git",
"svn_url": "https://github.com/ssettle3/Sass-Intro",
"homepage": null,
"size": 128,
"stargazers_count": 0,
"watchers_count": 0,
"language": "CSS",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
},
{
"id": 28971776,
"name": "Surf-Paddle",
"full_name": "ssettle3/Surf-Paddle",
"owner": {
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false
},
"private": false,
"html_url": "https://github.com/ssettle3/Surf-Paddle",
"description": "Homework Assignment 3 @ The Iron Yard",
"fork": false,
"url": "https://api.github.com/repos/ssettle3/Surf-Paddle",
"forks_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/forks",
"keys_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/teams",
"hooks_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/hooks",
"issue_events_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/issues/events{/number}",
"events_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/events",
"assignees_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/assignees{/user}",
"branches_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/branches{/branch}",
"tags_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/tags",
"blobs_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/languages",
"stargazers_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/stargazers",
"contributors_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/contributors",
"subscribers_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/subscribers",
"subscription_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/subscription",
"commits_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/issues/comments/{number}",
"contents_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/contents/{+path}",
"compare_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/merges",
"archive_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/downloads",
"issues_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/issues{/number}",
"pulls_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/labels{/name}",
"releases_url": "https://api.github.com/repos/ssettle3/Surf-Paddle/releases{/id}",
"created_at": "2015-01-08T15:22:49Z",
"updated_at": "2015-01-13T04:33:11Z",
"pushed_at": "2015-01-13T04:34:26Z",
"git_url": "git://github.com/ssettle3/Surf-Paddle.git",
"ssh_url": "git@github.com:ssettle3/Surf-Paddle.git",
"clone_url": "https://github.com/ssettle3/Surf-Paddle.git",
"svn_url": "https://github.com/ssettle3/Surf-Paddle",
"homepage": "",
"size": 4076,
"stargazers_count": 0,
"watchers_count": 0,
"language": "CSS",
"has_issues": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 0,
"mirror_url": null,
"open_issues_count": 0,
"forks": 0,
"open_issues": 0,
"watchers": 0,
"default_branch": "master"
}
]
var user = 
{
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false,
"name": "Stephen Settle",
"company": "",
"blog": "",
"location": "Atlanta, GA",
"email": "ssettle3@gmail.com",
"hireable": false,
"bio": null,
"public_repos": 13,
"public_gists": 0,
"followers": 1,
"following": 7,
"created_at": "2015-01-02T03:07:35Z",
"updated_at": "2015-01-26T18:17:24Z"
}
var org =
[
{
"login": "tiy-atl-js-q1-2015",
"id": 10352544,
"url": "https://api.github.com/orgs/tiy-atl-js-q1-2015",
"repos_url": "https://api.github.com/orgs/tiy-atl-js-q1-2015/repos",
"events_url": "https://api.github.com/orgs/tiy-atl-js-q1-2015/events",
"members_url": "https://api.github.com/orgs/tiy-atl-js-q1-2015/members{/member}",
"public_members_url": "https://api.github.com/orgs/tiy-atl-js-q1-2015/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/10352544?v=3",
"description": "The Iron Yard, Atlanta, January 2015"
}
]
var star = 
[]


// ==== Header User SECTION ====

var usrSm, usrSmString, usrSmFunct, usrSmHTML;

	usrSm = $('.userImgSm');
	usrSmString = $('#userSmTemp').html();
	usrSmFunct = _.template(usrSmString);
	usrSmHTML = usrSmFunct;
	usrSm.append(usrSmHTML(user))



// ==== User SECTION ====


var usr, templateString, templateFunct, templateHTML;

	usr = $('.user')
	templateString = $('#userTemp').html();
	templateFunct = _.template(templateString);
	templateHTML = templateFunct;
	usr.append(templateHTML(user))


// ==== Organization SECTION ====

var orgTIY, orgString, orgFunct, orgHTML;

	orgTIY = $('.orgs')
	orgString = $('#orgTemp').html();
	orgFunct = _.template(orgString);
	orgHTML = orgFunct;
	_.each(org, function(orgs){
		orgTIY.append(orgHTML(orgs))
	});


// ==== Repository SECTION ====


var repo, sortRepos, filtRepo, repoString, repoFunct, repoHTML, time, dateTime;


	// Sort Array to list repos in order of last updated
	sortRepos = repos.sort(function (a, b){
		if (a.updated_at < b.updated_at){
			return 1;
		}
		if (a.updated_at > b.updated_at){
			return -1;
		}
	});


	repo = $('.repos');
	repoString = $('#repoTemp').html();
	repoFunct = _.template(repoString);
	repoHTML = repoFunct;
	_.each(repos, function(sortRepos){
		repo.append(repoHTML(sortRepos))
	});



// ==== Date Stuff ====

var date, dt, dtt, dttt, year, month, day, hours, minutes, seconds;
	
	joined = $('.join');

	date = user.created_at;
	dt = date.split("-");
	year = dt[0];
	month = dt[1];
	dtt = dt[2].split("T");
	day = dtt[0];
	dttt = dtt[1].split(":");
	hours = dttt[0];
	minutes = dttt[1];

	joined.append("Joined on " + month + " " + day +", " + year);


